image: docker:latest

services:
    - docker:dind

frontend-build:
    stage: build
    script:
        - cd frontend
        - docker build -t frontend-test .
        - docker run frontend-test

complete-build:
    stage: build
    before_script:
        - apt install docker-compose
    script:
        - docker-compose up --build --scale backend=4
    after_script:
        - docker-compose down -v

deploy:
    stage: deploy
    before_script:
        - cd frontend
        - docker login -u brandonfox -p $gitlab_password
        - docker build -t registry.gitlab.com/brandonfox/backend-project-2-frontend
        - docker push registry.gitlab.com/brandonfox/backend-project-2-frontend