version: "3.7"

services:
    db:
        container_name: "Mysql-container"
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "backend4backend"
            MYSQL_USER: "server"
            MYSQL_PASS: "serverPass"
            MYSQL_DATABASE: "backenddb"

    backend:
        image: registry.gitlab.com/brandonfox/backend-project-2-backend
        
        environment: 
            MYSQL_HOST: "db"
            MYSQL_POST: 3306
        depends_on:
            - db

    frontend:
        links:
            - backend
        container_name: "Frontend-container"
        image: registry.gitlab.com/brandonfox/backend-project-2-frontend
        environment: 
            VUE_APP_BACKEND_PORT: 8080
    
    proxy:
        depends_on:
            - backend
            - frontend
        container_name: proxy
        image: brandon-proxy
        build:
            dockerfile: nginx.dockerfile
            context: .
        ports:
            - 8080:80

volumes:
    db_data:
